### ISSUE TITLE
Error in validating ENA samples against BioSamples dev

### ISSUE THREAD

**Issue by dipayan1985** [ebi-ait/checklist#163] opened 2024-11-05 15:56 UTC
```xml
<RECEIPT receiptDate="2024-11-05T15:53:31.351Z" submissionFile="submission-EBI_1730822011351.xml" success="false">
     <SAMPLE alias="2024_11_05_15_53_29_438__EBI_SUB_SRA_TEST_ALIAS__0" status="PRIVATE"/>
     <SUBMISSION alias="SUBMISSION-05-11-2024-15:53:30:572"/>
     <MESSAGES>
          <ERROR>2024_11_05_15_53_29_438__EBI_SUB_SRA_TEST_ALIAS__0 failed validation due to  Sample validation error: 500 Internal Server Error: [&lt;!doctype html>
&lt;html lang="en" class="vf-no-js">
  &lt;head>
    &lt;script>
// Detect if JS is on and swap vf-no-js for vf-js on the html element
(function(H){H.className=H.className.replace(/\bvf-no-js\b... (10135 bytes)]</ERROR>
          <ERROR>Failed to submit samples to BioSamples</ERROR>
          <ERROR>Failed to submit samples to BioSamples</ERROR>
          <ERROR>An exception occurred: java.lang.RuntimeException: Failed to submit all samples to BioSamples</ERROR>
     </MESSAGES>
     <ACTIONS>ADD</ACTIONS>
</RECEIPT>
```

**Comment by theisuru** [comment] 2024-11-05 16:40
Fixing some traffic manager problems. Will update once this is fixed. 

https://embl.service-now.com/esc?id=ticket&is_new_order=true&table=sc_req_item&sys_id=b9175afb1b659a503182bb35464bcbc0

**Comment by dipayan1985** [comment] 2024-11-06 10:30
Getting the error as below this morning:

`got response Sample validation error: 404 : [no body]`

Environment: wwwint BioSamples

@theisuru @amnonkhen

**Comment by dipayan1985** [comment] 2024-11-06 10:39
**Observation**: this error is for BSDC space checklists

**Comment by theisuru** [comment] 2024-11-06 11:32
Now problem with traffic manager is fixed. Probably we don't have BSD schecklists in this schema-store. Will look more today afternoon.

**Comment by dipayan1985** [comment] 2024-11-06 13:01
yes this explains the reason of BSD integration test failures as well as the BSDC checklists are unavailable.

**Comment by theisuru** [comment] 2024-11-06 16:52
@dipayan1985  Added BSDC checklists to wwwint environment. Tests are working for me now. Could you please check it with following config in BioSamples
`- biosamples.schemaStore=https://wwwint.ebi.ac.uk/biosamples/schema-store`

This is temporary measure. I have created a ticket to address the root cause ebi-ait/checklist#165

**Comment by theisuru** [comment] 2024-11-11 12:26
Closing this issue. Will track root cause in ebi-ait/checklist#165

**Closed as completed** 2024-11-11 12:26 UTC
Labels: FAIRification, checklist, Submissions
